# Generated by Django 6.0.4 on 2026-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_official_store',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor',
            new_name='is_student_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
