# Generated by Django 6.0.4 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_is_student_user_is_official_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_specialty',
            field=models.CharField(blank=True, help_text='e.g. Laptops & IT Solutions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Main Campus, Room 12', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to Instagram or Website', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.CharField(blank=True, default='Mon-Fri, 8AM - 6PM', max_length=100, null=True),
        ),
    ]
