# Generated by Django 6.0.4 on 2026-05-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_specialty', models.CharField(help_text='e.g., Fast Food, Electronics', max_length=100)),
                ('physical_location', models.CharField(help_text='Where is your shop located?', max_length=255)),
                ('merchant_code', models.CharField(help_text='Enter your Merchant or Till Number', max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
