# Generated by Django 6.0.4 on 2026-05-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='momo_transaction_id',
            field=models.CharField(blank=True, help_text='The ID from the MoMo/Airtel SMS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('VERIFYING', 'Verifying MoMo ID'), ('IN_ESCROW', 'Money in Escrow (OTP Generated)'), ('COMPLETED', 'Delivered & Paid Out'), ('CANCELLED', 'Cancelled/Refunded')], default='PENDING', max_length=20),
        ),
    ]
